site_name: YeastSAM
site_description: Detailed Documentation for YeastSAM
site_author: Yonghao Zhao

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - header.social
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_url: https://github.com/YonghaoZhao722/YeastSAM
repo_name: GitHub

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YonghaoZhao722/YeastSAM
